### ISSUE TITLE
Fatal Error Calling Mailgun

### ISSUE THREAD

**Issue by JoelSParker** [ttskch/monolog-mailgun#1]
I am receiving the following error
`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Ttskch\Monolog\Handler\MailgunHandler::__construct() must be an instance of Mailgun\Mailgun, string given`

Below is the code:
```yaml
### /prod/monolog.yml
services:
    mailgun:
        class: Mailgun\Mailgun
        factory: [Mailgun\Mailgun, create]
        arguments: ['%env(MAILGUN_API_KEY)%']
    mailgun_handler:
        class: Ttskch\Monolog\Handler\MailgunHandler
        arguments:
            - mailgun
```
